from sqlalchemy import Column, DateTime, Integer, String, Float
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class TuroTripsTable(Base):
    __tablename__ = 'trips'
    id = Column(Integer, primary_key=True, autoincrement=True)
    reservation_id = Column(Integer)
    guest = Column(String)
    vehicle = Column(String)
    vehicle_name = Column(String)
    vehicle_nickname = Column(String)
    vehicle_id = Column(Integer)
    vin = Column(String)
    trip_start = Column(DateTime)
    trip_end = Column(DateTime)
    pickup_location = Column(String)
    return_location = Column(String)
    trip_status = Column(String)
    check_in_odometer = Column(Integer)
    check_out_odometer = Column(Integer)
    distance_traveled = Column(Integer)
    trip_days = Column(Integer)
    trip_price = Column(Float)
    boost_price = Column(Float)
    three_day_discount = Column(Float)
    one_week_discount = Column(Float)
    two_week_discount = Column(Float)
    three_week_discount = Column(Float)
    one_month_discount = Column(Float)
    two_month_discount = Column(Float)
    three_month_discount = Column(Float)
    non_refundable_discount = Column(Float)
    early_bird_discount = Column(Float)
    host_promotional_credit = Column(Float)
    delivery = Column(Float)
    excess_distance = Column(Float)
    extras = Column(Float)
    cancellation_fee = Column(Float)
    additional_usage = Column(Float)
    late_fee = Column(Float)
    improper_return_fee = Column(Float)
    airport_operations_fee = Column(Float)
    airport_parking_credit = Column(Float)
    tolls_and_tickets = Column(Float)
    on_trip_ev_charging = Column(Float)
    post_trip_ev_charging = Column(Float)
    smoking = Column(Float)
    cleaning = Column(Float)
    fines_paid_to_host = Column(Float)
    gas_reimbursement = Column(Float)
    gas_fee = Column(Float)
    other_fees = Column(Float)
    sales_tax = Column(Float)
    total_earnings = Column(Float)
